spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/restaurantreservation
    driver-class-name: org.mariadb.jdbc.Driver
    username: restaurantreservation_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
