spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/shopreservation
    driver-class-name: org.mariadb.jdbc.Driver
    username: shopreservation_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: cmVzdGF1cmFudC1yZXNlcnZhdGlvbi1zeXN0ZW0tc2VjcmV0LWtleS1hbmQtdGhpcy1zaG91bGQtYmUtbW9yZS1sZW5ndGh5Cg==

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.security: DEBUG
